import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Merriweather, Playfair_Display } from "next/font/google";
import "./globals.css";
import ClientBody from "./client-body";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});
const merriweather = Merriweather({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-alt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} ${merriweather.variable}`}
      >
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}
